### ISSUE TITLE
Exposure compensation and tap to exposure

### ISSUE THREAD

**Issue by StefanoV1989** [Lightsnap/flutter_better_camera#7]
Hi,
Can you add the exposure compensation function?
I saw the complete code on a pull request of flutter "camera" plugin.
So you just need to copy/paste the code.
I already did it with standard flutter camera, but I think I'll do it again using this better_camera as starting point (so I could have more features).

But after that, I'd like to ask you if you can implement a tap to exposure function (like tap to focus but for exposure) that works with exposure compensation mentioned before.

In this way I can tap on dark areas of my picture to expose there, and then compensate with +2 for example.

Thank you in advance.

**Comment by gummie4444** [comment]
Will add a task for this
